[package]
name = "exploit_poc_tests"
version = "0.1.0"
edition = "2021"

[workspace]
members = []

[dependencies]
cosmwasm-std = "2.1.4"
cw-storage-plus = "2.0.0"
serde = { version = "1.0", features = ["derive"] }

[[test]]
name = "exploit_poc_tests"
path = "exploit_poc_tests.rs"